set(CMAKE_SYSTEM_NAME Windows)
set(TOOLCHAIN_PREFIX x86_64-w64-mingw32)

set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)
set(CMAKE_RC_COMPILER ${TOOLCHAIN_PREFIX}-windres)

set(CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# Compilation
set(BUILD_SHARED_LIBS OFF)
set(OPTION_SELF_CONTAINED OFF)
set(OPTION_BUILD_TESTS OFF)
set(OPTION_BUILD_DOCS OFF)
set(OPTION_BUILD_TOOLS OFF)
set(OPTION_BUILD_EXAMPLES OFF)
set(OPTION_BUILD_WITH_BOOST_THREAD OFF)
set(OPTION_BUILD_CHECK OFF)
set(OPTION_BUILD_OWN_KHR_HEADERS OFF)
set(OPTION_BUILD_WITH_LTO OFF)

